menu:
  Docs: /docs/
  API: https://github.com/xsmart/ve
  News: /news/
  Download: http://sourceforge.net/projects/vscloud/
  Contact: /docs/contact.html

doc_sidebar:
  Getting Started:
    Overview: index.html
    Setup: setup.html
  Device Management:
    Camera: camera.html
    Disk: disk.html
    Virtual IPC: vipc.html
  View Management:
    Layout: layout.html
    Multi Screen: mscreen.html
    View : view.html
  Recording & Playback:
    Recording: recording.html
    HDFS Recording: hdfsrecording.html
    Playback: playback.html
  Data Mining:
    People Counting: pcounting.html
    Smart Search: smartsearch.html
  Contact:
    Contact: contact.html

google_analytics: 
fb_admins: 
swiftype_key: 
twitter: xsmart
github: xsmart/ve